### ISSUE TITLE
how to see the test result in csv , where are the results are stored in csv for testing

### ISSUE THREAD

**Issue by ghost** [joeloskarsson/CGAN-regression#10]
Hi,

I am trying to train on custom data, the model trains and test using the command and making the test flag to 1. but I can not find the results saved somewhere.
Could you please give me direction?
Thank you

**Comment by joeloskarsson** [comment]
Hi, make sure to read the section https://github.com/joeloskarsson/CGAN-regression#weights-and-biases-integration carefully, as I think that might answer your question. In short, the project is set up to log to Weights & Biases. Assuming that you are not using Weights & Biases and have then ran `wandb off`, the results are logged in a directory called something like `wandb/dryrun-2020...wandb/dryrun-2020...`. The exact path should be printed when the script is ran. Many things are also directly printed to std.-out. 

Depending on the exact results/metrics you want to collect you might find it in the places mentioned above, otherwise you'll have to extend the implementation to save the things you want.
