### ISSUE TITLE
how to use custom data

### ISSUE THREAD

**Issue by ghost** [joeloskarsson/CGAN-regression#9]
HI ,
I want to implement custom dataset in this work. is it possible please?
a sample of the data is given here
[data(2).csv]
(https://github.com/joeloskarsson/CGAN-regression/files/9032823/data.2.csv)
target is power
Which dataset will be like this to implement.
thank you for the time

**Comment by joeloskarsson** [comment]
Hi! 
In order to use some custom dataset it is probably easiest to pre-process it in the same way as the existing datasets. You can do this by implementing a custom class and putting it in the `dataset_specifications` directory. See for example https://github.com/joeloskarsson/CGAN-regression/blob/master/dataset_specifications/housing.py (or any other specification class in there) for how such a class can look like. Note 1) that real-world dataset are handled differently than synthetic ones, with different methods in the specification class 2) that features and targets are concatenated in the same dataframe when returned from the pre-processing method. 

Then you would have to add that class to the list in `dataset_list.py`. This should allow for pre-processing the dataset and then using it to train models.
